name: Notify Main Repo

on:
  push:
    branches: [ main ]

jobs:
  trigger-main:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MAIN_REPO_TOKEN }}" \
            https://api.github.com/repos/slnq/page/dispatches \
            -d '{"event_type":"submodule-updated"}'
